# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none
#- master

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'
      demands:
      - msbuild
      - visualstudio
      - vstest

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      # ResourceGroupName: 'PartsUnlimitedRG'
      # WebsiteName: 'pule2e0da0d460'
      # ServerName: 'pule2e0da0d460'
      # HostingPlan: 'pule2e'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    # - task: VSBuild@1
    #   inputs:
    #     solution: '$(solution)'
    #     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'
    - task: VSBuild@1
      inputs:
        solution: '**/*.csproj'
        enabled: true

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)/PartsUnlimited-aspnet45/env/'
        Contents: '**/*.json'
        TargetFolder: '$(build.artifactstagingdirectory)'    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: Hosted VS2017
    steps:
        
    - task: DownloadPipelineArtifact@2
      displayName: Download Build Artifacts
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy Resource Group 
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'ES-CE-LR-INT REQUESTORALIAS (6a92d24c-701c-4ec5-8af0-7981e6537707)'
        subscriptionId: '6a92d24c-701c-4ec5-8af0-7981e6537707'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(RgName)'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.ArtifactsDirectory)/**/FullEnvironmentSetupMerged.json'
        csmParametersFile: '$(System.ArtifactsDirectory)/**/FullEnvironmentSetupMerged.param.json'
        overrideParameters: '-WebsiteName $(WebsiteName) -PUL_ServerName $(PUL_ServerName) -PUL_DBPassword $(PUL_DBPassword) -PUL_DBPasswordForTest $(PUL_DBPasswordForTest) -PUL_HostingPlanName $(PUL_HostingPlanName)' 
        # overrideParameters: |
        #   -WebsiteName $(WebsiteName) -PUL_ServerName
        #   $(PUL_ServerName) -PUL_DBPassword $(PUL_DBPassword) -PUL_DBPasswordForTest
        #   $(PUL_DBPasswordForTest) -PUL_HostingPlanName $(PUL_HostingPlanName)
        deploymentMode: 'Incremental'
#   variables:
#   ResourceGroupName: 'ASPDOTNET'
#   WebsiteName: 'pule2e0da0d460'
#   ServerName: 'pule2e0da0d460'
#   HostingPlan: 'pule2e'

# steps:
# - task: AzureResourceGroupDeployment@2
#   displayName: 'Azure Deployment'
#   inputs:
#     azureSubscription: 'ES-CE-LR-INT REQUESTORALIAS (6a92d24c-701c-4ec5-8af0-7981e6537707)'
#     resourceGroupName: '$(ResourceGroupName)'
#     location: 'West US'
#     csmFile: '$(System.DefaultWorkingDirectory)/PartsUnlimitedE2E/drop/PartsUnlimited-aspnet45/env/PartsUnlimitedEnv/Templates/FullEnvironmentSetupMerged.json'
#     csmParametersFile: '$(System.DefaultWorkingDirectory)/PartsUnlimitedE2E/drop/PartsUnlimited-aspnet45/env/PartsUnlimitedEnv/Templates/FullEnvironmentSetupMerged.param.json'
#     overrideParameters: '-WebsiteName $(WebsiteName) -PUL_ServerName $(ServerName)  -PUL_HostingPlanName $(HostingPlan)'    