trigger:
  batch: true
  branches:
    include: 
      - 'master'
  paths:
    exclude:
      - README.md  
name: workloadName_$(BuildDefinitionName)_$(Build.SourceBranchName)_$(Date:yyyyMMdd).$(Rev:rr)      

stages:
- stage: build

  jobs:
  - template: /pipelines/job_templates/build.yml
    parameters: 
      preBuildSteps: []
      buildConfigurations: 'release'

- template: /pipelines/stage_templates/deployworkload.yml  
  parameters:
    workloadName: 'workload-prod-fa'

- stage: configure
  #dependsOn: Deploy
  jobs:
  - job: deploy_staging   
    pool:
      vmImage: 'ubintu-latest'
    steps:
    - script: echo "Configure"  


  
