/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Products]
(
[ProductId] [int] NOT NULL IDENTITY(1, 1),
[SkuNumber] [nvarchar] (max) NOT NULL,
[CategoryId] [int] NOT NULL,
[RecommendationId] [int] NOT NULL,
[Title] [nvarchar] (160) NOT NULL,
[Price] [decimal] (18, 2) NOT NULL,
[SalePrice] [decimal] (18, 2) NOT NULL,
[ProductArtUrl] [nvarchar] (1024) NULL,
[Description] [nvarchar] (max) NOT NULL,
[Created] [datetime] NOT NULL,
[ProductDetails] [nvarchar] (max) NOT NULL,
[Inventory] [int] NOT NULL,
[LeadTime] [int] NOT NULL,
[PriceUSD ] [decimal] (18, 2) NULL
)
GO
ALTER TABLE [dbo].[Products] ADD CONSTRAINT [PK_dbo.Products] PRIMARY KEY CLUSTERED ([ProductId])
GO
ALTER TABLE [dbo].[Products] ADD CONSTRAINT [FK_dbo.Products_dbo.Categories_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([CategoryId]) ON DELETE CASCADE
GO
