/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Orders]
(
[OrderId] [int] NOT NULL IDENTITY(1, 1),
[OrderDate] [datetime] NOT NULL,
[Username] [nvarchar] (max) NOT NULL,
[Name] [nvarchar] (160) NOT NULL,
[Address] [nvarchar] (70) NOT NULL,
[City] [nvarchar] (40) NOT NULL,
[State] [nvarchar] (40) NOT NULL,
[PostalCode] [nvarchar] (10) NOT NULL,
[Country] [nvarchar] (40) NOT NULL,
[Phone] [nvarchar] (24) NOT NULL,
[Email] [nvarchar] (max) NOT NULL,
[Total] [decimal] (18, 2) NOT NULL
)
GO
ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [PK_dbo.Orders] PRIMARY KEY CLUSTERED ([OrderId])
GO
