/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Stores]
(
[StoreId] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (max) NULL
)
GO
ALTER TABLE [dbo].[Stores] ADD CONSTRAINT [PK_dbo.Stores] PRIMARY KEY CLUSTERED ([StoreId])
GO
