parameters:
- name: buildConfigurations
  displayName: Build Configurations
  type: string
  default: 'release'
  values: 
  - 'debug'
  - 'release'

- name: preBuildSteps
  displayName: Pre Build Steps
  type: stepList
  default: []

jobs:
- job: run_build
  pool: 
    name: Hosted VS2017
  steps:
  - ${{ parameters.preBuildSteps }}  
  - bash: echo "Build with ${{ parameters.buildConfigurations }}"